const SUPABASE_URL="https://jixzylyukugyixtodqec.supabase.co";const SUPABASE_KEY="sb_publishable_rCQZskarlFNj4D5cdne_Rw_QDXX4wcB";let supabase=null,items=[],editId=null;const $=id=>document.getElementById(id);
async function boot(){const {createClient}=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");supabase=createClient(SUPABASE_URL,SUPABASE_KEY);const {data:{session}}=await supabase.auth.getSession();if(session)await enterAdmin();else showLogin();supabase.auth.onAuthStateChange(async(_,session)=>{if(session)await enterAdmin();else showLogin()})}
function showLogin(){$("authBox").classList.remove("hidden");$("adminApp").classList.add("hidden")}
async function enterAdmin(){const {data:{user}}=await supabase.auth.getUser();const {data,error}=await supabase.from("hub_admins").select("user_id").eq("user_id",user.id).maybeSingle();if(error||!data){$("authError").textContent="This account is not authorized for SriVerse Hub.";await supabase.auth.signOut();return}$("authBox").classList.add("hidden");$("adminApp").classList.remove("hidden");await loadItems()}
async function loadItems(){const {data,error}=await supabase.from("destinations").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:false});if(error){$("status").textContent="Database error";alert(error.message);return}items=data||[];render()}
function render(){const q=$("adminSearch").value.toLowerCase();const shown=items.filter(x=>(x.title+" "+x.description+" "+x.category).toLowerCase().includes(q));$("total").textContent=items.length;$("featured").textContent=items.filter(x=>x.featured).length;$("live").textContent=items.filter(x=>x.live).length;$("status").textContent="Supabase connected";$("adminList").innerHTML=shown.map(x=>`<div class="admin-row"><div class="admin-icon">${x.icon}</div><div><h3>${x.title}</h3><p>${x.description}</p><div class="badges"><span class="badge">${x.category}</span>${x.featured?'<span class="badge">FEATURED</span>':""}${x.live?'<span class="badge">LIVE</span>':'<span class="badge">DRAFT</span>'}</div></div><div class="row-actions"><button onclick="editItem('${x.id}')">Edit</button><button class="delete" onclick="deleteItem('${x.id}')">Delete</button></div></div>`).join("")||'<div class="empty">No destinations found.</div>'}
function openModal(item){editId=item?.id||null;$("modalTitle").textContent=editId?"Edit destination":"Add destination";$("fTitle").value=item?.title||"";$("fDesc").value=item?.description||"";$("fUrl").value=item?.url&&item.url!="#"?item.url:"";$("fCategory").value=item?.category||"Projects";$("fIcon").value=item?.icon||"✦";$("fFeatured").checked=!!item?.featured;$("fLive").checked=item?item.live!==false:true;$("modal").hidden=false}
async function editItem(id){openModal(items.find(x=>x.id===id))}
async function deleteItem(id){if(!confirm("Delete this destination?"))return;const {error}=await supabase.from("destinations").delete().eq("id",id);if(error){alert(error.message);return}await loadItems()}
$("authForm").onsubmit=async e=>{e.preventDefault();$("authError").textContent="";const {error}=await supabase.auth.signInWithPassword({email:$("authEmail").value.trim(),password:$("authPassword").value});if(error)$("authError").textContent=error.message};$("logoutBtn").onclick=()=>supabase.auth.signOut();$("newBtn").onclick=()=>openModal();$("close").onclick=$("cancel").onclick=()=>{$("modal").hidden=true};$("adminSearch").oninput=render;
$("form").onsubmit=async e=>{e.preventDefault();const title=$("fTitle").value.trim(),description=$("fDesc").value.trim(),url=$("fUrl").value.trim()||"#",category=$("fCategory").value,icon=$("fIcon").value.trim()||"✦",featured=$("fFeatured").checked,live=$("fLive").checked;let result;if(editId)result=await supabase.from("destinations").update({title,description,url,category,icon,featured,live}).eq("id",editId);else{const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||crypto.randomUUID();result=await supabase.from("destinations").insert({id:crypto.randomUUID(),slug,title,description,url,category,icon,featured,live,sort_order:items.length+10,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})}if(result.error){alert(result.error.message);return}$("modal").hidden=true;await loadItems()};window.editItem=editItem;window.deleteItem=deleteItem;boot().catch(e=>{console.error(e);$("authError").textContent="Unable to load the admin system."});